In [3]:
import os
os.chdir(r"B:\12RossyDocumentos\12ProyectoGallinas\11Avance\13_proyecto_gallinas")

import pandas as pd
from siuba import *

# Modelo Baseline

In [4]:
DataBase11 = pd.read_csv("artifacts/data_comparativa_baseline.csv")
DataBase11

,epocas_inicial,epocas_fin,batch,learning_rate,optimizer,total_imagenes,total_imagenes_train,total_imagenes_val,tiempo_minutos,tiempo_horas,map50,map50_95,precision,recall
0,50,50,8,0.01,SGD,63,50,13,1.025633,0.017044,0.556,0.1823,0.6099,0.58356

In [5]:
DataBase12 = (
    DataBase11
    >> mutate(
        modelo = "yolo26m"
    )
)
DataBase12

,epocas_inicial,epocas_fin,batch,learning_rate,optimizer,total_imagenes,total_imagenes_train,total_imagenes_val,tiempo_minutos,tiempo_horas,map50,map50_95,precision,recall,modelo
0,50,50,8,0.01,SGD,63,50,13,1.025633,0.017044,0.556,0.1823,0.6099,0.58356,yolo26m

# Modelos Iniciales

In [6]:
DataEva11 = pd.read_csv("artifacts/data_comparativa_modelos_11.csv")
DataEva11

,epocas_inicial,epocas_fin,batch,learning_rate,optimizer,total_imagenes,total_imagenes_train,total_imagenes_val,tiempo_minutos,tiempo_horas,map50,map50_95,precision,recall
0,150,150,8,0.010,SGD,63,50,13,3.182633,0.053044,0.62927,0.22499,0.66027,0.65241
1,150,150,6,0.010,SGD,63,50,13,3.722767,0.062046,0.63592,0.22440,0.68010,0.63168
2,150,150,10,0.010,SGD,63,50,13,2.784250,0.046404,0.63515,0.22378,0.67402,0.65709
3,150,150,12,0.010,SGD,63,50,13,2.827133,0.047119,0.63468,0.22166,0.67730,0.62968
4,100,100,6,0.001,AdamW,63,50,13,2.865367,0.047756,0.61625,0.21575,0.64591,0.60481
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,150,150,12,0.100,AdamW,63,50,13,5.929683,0.098828,0.02256,0.00422,0.07179,0.18717
68,50,50,6,0.100,AdamW,63,50,13,2.458800,0.040980,0.01589,0.00271,0.06201,0.13904
69,150,150,6,0.100,AdamW,63,50,13,6.772117,0.112869,0.01648,0.00264,0.06900,0.15709
70,100,100,6,0.100,AdamW,63,50,13,4.791633,0.079861,0.01637,0.00263,0.07873,0.10963
71,50,50,8,0.100,AdamW,63,50,13,1.443562,0.024059,0.01021,0.00171,0.05513,0.14372

In [7]:
DataEva12 = (
    DataEva11
    >> mutate(
        modelo = "yolo26m"
    )
)
DataEva12

,epocas_inicial,epocas_fin,batch,learning_rate,optimizer,total_imagenes,total_imagenes_train,total_imagenes_val,tiempo_minutos,tiempo_horas,map50,map50_95,precision,recall,modelo
0,150,150,8,0.010,SGD,63,50,13,3.182633,0.053044,0.62927,0.22499,0.66027,0.65241,yolo26m
1,150,150,6,0.010,SGD,63,50,13,3.722767,0.062046,0.63592,0.22440,0.68010,0.63168,yolo26m
2,150,150,10,0.010,SGD,63,50,13,2.784250,0.046404,0.63515,0.22378,0.67402,0.65709,yolo26m
3,150,150,12,0.010,SGD,63,50,13,2.827133,0.047119,0.63468,0.22166,0.67730,0.62968,yolo26m
4,100,100,6,0.001,AdamW,63,50,13,2.865367,0.047756,0.61625,0.21575,0.64591,0.60481,yolo26m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,150,150,12,0.100,AdamW,63,50,13,5.929683,0.098828,0.02256,0.00422,0.07179,0.18717,yolo26m
68,50,50,6,0.100,AdamW,63,50,13,2.458800,0.040980,0.01589,0.00271,0.06201,0.13904,yolo26m
69,150,150,6,0.100,AdamW,63,50,13,6.772117,0.112869,0.01648,0.00264,0.06900,0.15709,yolo26m
70,100,100,6,0.100,AdamW,63,50,13,4.791633,0.079861,0.01637,0.00263,0.07873,0.10963,yolo26m
71,50,50,8,0.100,AdamW,63,50,13,1.443562,0.024059,0.01021,0.00171,0.05513,0.14372,yolo26m

# Eval modelos yolo's

In [8]:
DataVarios11 = pd.read_csv("artifacts/data_comparativa_modelos_12.csv")
DataVarios11

,epocas_inicial,epocas_fin,modelo,batch,learning_rate,optimizer,total_imagenes,total_imagenes_train,total_imagenes_val,tiempo_minutos,tiempo_horas,map50,map50_95,precision,recall
0,200,200,yolo26m,8,0.1,SGD,63,50,13,3.716017,0.061934,0.48715,0.15321,0.58392,0.48329
1,150,150,yolo26m,6,0.1,SGD,63,50,13,3.232550,0.053876,0.28806,0.07925,0.39453,0.37500
2,200,200,yolo12m,8,0.1,SGD,63,50,13,3.660550,0.061009,0.27605,0.07074,0.34061,0.41644
3,200,200,yolo11m,6,0.1,AdamW,63,50,13,4.498100,0.074968,0.22669,0.05572,0.24734,0.48061
4,150,150,yolo12m,8,0.1,SGD,63,50,13,2.836833,0.047281,0.22280,0.05229,0.23334,0.47126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,200,101,yolo26m,8,0.5,AdamW,63,50,13,2.461950,0.041032,0.00307,0.00108,0.02923,0.07620
60,150,101,yolo26m,6,0.5,SGD,63,50,13,2.164967,0.036083,0.00276,0.00094,0.02872,0.07487
61,150,101,yolo26m,6,0.5,AdamW,63,50,13,2.611633,0.043527,0.00276,0.00094,0.02872,0.07487
62,200,101,yolo26m,6,0.5,SGD,63,50,13,2.119883,0.035331,0.00276,0.00094,0.02872,0.07487
63,200,101,yolo26m,6,0.5,AdamW,63,50,13,2.538733,0.042312,0.00276,0.00094,0.02872,0.07487

## Union

In [9]:
DataUnion11 = pd.concat([DataBase12, DataEva12, DataVarios11])
DataUnion11

,epocas_inicial,epocas_fin,batch,learning_rate,optimizer,total_imagenes,total_imagenes_train,total_imagenes_val,tiempo_minutos,tiempo_horas,map50,map50_95,precision,recall,modelo
0,50,50,8,0.01,SGD,63,50,13,1.025633,0.017044,0.55600,0.18230,0.60990,0.58356,yolo26m
0,150,150,8,0.01,SGD,63,50,13,3.182633,0.053044,0.62927,0.22499,0.66027,0.65241,yolo26m
1,150,150,6,0.01,SGD,63,50,13,3.722767,0.062046,0.63592,0.22440,0.68010,0.63168,yolo26m
2,150,150,10,0.01,SGD,63,50,13,2.784250,0.046404,0.63515,0.22378,0.67402,0.65709,yolo26m
3,150,150,12,0.01,SGD,63,50,13,2.827133,0.047119,0.63468,0.22166,0.67730,0.62968,yolo26m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,200,101,8,0.50,AdamW,63,50,13,2.461950,0.041032,0.00307,0.00108,0.02923,0.07620,yolo26m
60,150,101,6,0.50,SGD,63,50,13,2.164967,0.036083,0.00276,0.00094,0.02872,0.07487,yolo26m
61,150,101,6,0.50,AdamW,63,50,13,2.611633,0.043527,0.00276,0.00094,0.02872,0.07487,yolo26m
62,200,101,6,0.50,SGD,63,50,13,2.119883,0.035331,0.00276,0.00094,0.02872,0.07487,yolo26m
63,200,101,6,0.50,AdamW,63,50,13,2.538733,0.042312,0.00276,0.00094,0.02872,0.07487,yolo26m

In [10]:
DataUnion12 = (
    DataUnion11
    >> distinct()
    >> arrange(-_.map50_95)
)
DataUnion12

,epocas_inicial,epocas_fin,batch,learning_rate,optimizer,total_imagenes,total_imagenes_train,total_imagenes_val,tiempo_minutos,tiempo_horas,map50,map50_95,precision,recall,modelo
1,150,150,8,0.010,SGD,63,50,13,3.182633,0.053044,0.62927,0.22499,0.66027,0.65241,yolo26m
2,150,150,6,0.010,SGD,63,50,13,3.722767,0.062046,0.63592,0.22440,0.68010,0.63168,yolo26m
3,150,150,10,0.010,SGD,63,50,13,2.784250,0.046404,0.63515,0.22378,0.67402,0.65709,yolo26m
4,150,150,12,0.010,SGD,63,50,13,2.827133,0.047119,0.63468,0.22166,0.67730,0.62968,yolo26m
5,100,100,6,0.001,AdamW,63,50,13,2.865367,0.047756,0.61625,0.21575,0.64591,0.60481,yolo26m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,200,101,8,0.500,AdamW,63,50,13,2.461950,0.041032,0.00307,0.00108,0.02923,0.07620,yolo26m
133,150,101,6,0.500,SGD,63,50,13,2.164967,0.036083,0.00276,0.00094,0.02872,0.07487,yolo26m
134,150,101,6,0.500,AdamW,63,50,13,2.611633,0.043527,0.00276,0.00094,0.02872,0.07487,yolo26m
135,200,101,6,0.500,SGD,63,50,13,2.119883,0.035331,0.00276,0.00094,0.02872,0.07487,yolo26m
136,200,101,6,0.500,AdamW,63,50,13,2.538733,0.042312,0.00276,0.00094,0.02872,0.07487,yolo26m

In [11]:
(
    DataUnion12
    >> group_by(_.modelo)
    >> summarize(
        val_max = _.map50_95.max()
        , val_min = _.map50_95.min()
    )
    >> ungroup()
    >> arrange(-_.val_max)
)

b:\12RossyDocumentos\12ProyectoGallinas\11Avance\13_proyecto_gallinas\.venv\Lib\site-packages\siuba\dply\verbs.py:561: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = __data.apply(df_summarize, *args, **kwargs)

     modelo  val_max  val_min
2   yolo26m  0.22499  0.00094
1   yolo12m  0.07074  0.00202
0   yolo11m  0.05572  0.00294
3  yolov10m  0.04143  0.00776